config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  root 'static_page#index'

  get 'sobre', to: 'static_page#sobre'
  get 'contato', to: 'static_page#contato'

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  before_save :email_downcase

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: true }


  private
    def email_downcase
      self.email.downcase!
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Email e Senha invalidos'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Logout realizado com sucesso'
    redirect_to entrar_path
  end

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  
  def index
  end

  def Sobre
  end

  def contato
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:sucess] = 'Cadastro realizado com sucesso'
      redirect_to users_url
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for_email(email, options = { size: 80, class: 'img-circle img-responsive center-block' })
    gravatar_digest = Digest::MD5::hexdigest(email.downcase)
    size = options[:size]
    html_class = options = options[:class]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_digest}?s=#{size}"
    image_tag(gravatar_url, class: html_class)
  end

end

app/views/layouts/_footer.html.erb
<footer>
	<small>
		<%= link_to 'FotoShare. Todos os direitos reservados', root_path %>
	</small>
	<nav>
		<ul>
			<li>
				<%= link_to 'sobre', sobre_path %>
			</li>
			<li>
				<%= link_to 'contato', contato_path %>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FotoShare', root_url, class: 'navbar-brand' %>
    </div>

  <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
  <div class="collapse navbar-collapse" id="expanded-menu">
    <ul class="nav navbar-nav">
      <% if !user_signed_in? %>
      <li class="active">
        <a href="#">Nova Conta</a>
      </li>
      <% end %>
    </ul>

    <% if user_signed_in? %>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="buscar amigo">
          <input type="submit" value="buscar" class="btn btn-default">
        </div>
      </form>
    <% end %>

    <ul class="nav navbar-nav navbar-right">
      <% if !user_signed_in? %>
        <li>
          <%= link_to 'Entrar', entrar_path %>
        </li>
      <% end %>

      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            bem vindo, <%= current_user.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Minha Pagina', current_user %>
            </li>
            <li>
              <%= link_to 'Editar', edit_user_path(current_user) %>
            </li>
            <li class="divider" role="separator"></li>
            <li>
              <%= link_to 'Sair', sair_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% end %>
    </ul>

  </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photoshare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">

    <% flash.each do |message_type, message| %>
      <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
        <button type="button" class="close" data-mismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
        <% end %>
      <% end %>
    
      <%= yield %>
    
    
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div class="">
	<div class="alert alert-danger">
		Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
			<% end %>		
		</ul>
	</div>
</div>
<% end %>

app/views/static_page/contato.html.erb
<h1>Contato</h1>

<p>
	Entre em contato com <a href="http://twitter.com/govannyolimpio">@geovannyolimpio</a> para saber mais.
</p>

app/views/static_page/index.html.erb
<div class="jumbotron">
	<h1>FotoShare</h1>
	<p>
		Compartilhe seus melhores momentos.
	</p>
	<p>
		<a href="#" class="btn btn-primary btn-lg">Crie sua conta!</a>
	</p>
</div>

<div class="row">
<% for i in 0...6 do %>
<div class="col-xs-12 col-md-4 col-lg-4">
	<div class="thumbnail post-card">
		<%= image_tag 'natureza.jpg', class: 'img img-responsive post' %>
	</div>
	<div class="caption">
		<%= image_tag 'natureza.jpg', class: 'img img-rounded', style: 'width: 30px; height: 30px;' %>
		<div class="post-legenda">
			<span>Postado por fulano de Tal</span> <br>
			<span>2 horas atras</span>
		</div>
		<div class="Legenda">
			<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			</p>
		</div>
	</div>
</div>
<% end %>	
</div>

app/views/static_page/sobre.html.erb
<h1>Sobre</h1>

<p>
	Aqui um pouco o app FotoShare desenvolvido no curso de Ruby on Rails.
</p>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
	<%= f.label :email %>
	<%= f.text_field :email, class: 'form-control' %>
</div>

<div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>
</div>

<div class="form-group">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

app/views/users/_user.html.erb
<div class="user-info">
  <div class="user-avatar col-md-4 col-sm-3 col-xs-12">
    <%= gravatar_for_email(user.email) %>
  </div>

  <div class="user-data col-md-8 col-sm-9 col-xs-12">
    <ul class="user-data">
      <li>
        <%= link_to user do %>
          <span class="username"><%= user.name %></span>
        <% end %>
      </li>
      <li>
        <a href="#">
          <span class="label label-pill label-primary">50</span>
          Seguindo
        </a>
      </li>
      <li>
        <a href="#">
          <span class="label label-pill label-success">55</span>
          Seguidores
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row">
	<div class="col-xs-12">
		<h1>Cadatra-se</h1>
	</div>

	<div class="col-md-6 col-md-offset-3 col-xs-12">
	<%= form_for @user do |f| %>
		<%= render 'fields', f: f %>

		<%= f.submit 'cadastrar', class: 'btn btn-primary' %>
	<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">

  <div class="col-xs-12 col-sm-12 col-md-4">
    <%= render @user %>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-8">
    <h2>Fotos Postadas por <%= @user.name %></h2>
  </div>

</div>